blog:
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  email: mail@mail.ru
  phone: +7 903 666-44-55
  subtitle: Рассказы разработчиков
  title: DevPub
spring:
  datasource:
    password: Qazwsx12344321
    url: jdbc:mysql://localhost:3306/website?serverTimezone=UTC#?allowPublicKeyRetrieval=true&amp;shutdown=true&amp;useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:/data/changelog/db.changelog.master.xml
    enabled: true
  thymeleaf:
    prefix: classpath:templates/
  web:
    resources:
      static-locations: classpath:templates/
